### ISSUE TITLE
RFE: Adding libyaml-devel

### ISSUE THREAD

**Issue by LalatenduMohanty** [LalatenduMohanty/centos7-container-app-vagrant-box#12]
As per Langdon's suggestion we need to add  libyaml-devel to the ks file. As atomicapp has a dependency on it.

**Comment by langdon** [comment]
Weirdly, when I did it the first time, that was enough. I just tried it again and I need PyYAML & libyaml-devel.

**Comment by kbsingh** [comment]
We should add the entire dep chain, but maybe we just need the dep chain ? for example: we carry the entire @development group, that includes the entire gcc toolchain as well. Do we need all that ?

ref: https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/18

**Comment by LalatenduMohanty** [comment]
@kbsingh not sure if we really need @development group. Once we have fair understanding of the dependency chain for atomicapp we can try removing it.

**Comment by LalatenduMohanty** [comment]
PyYAML & libyaml-devel thing will be fixed in the next rebuild of the vagrant box

**Comment by langdon** [comment]
@development makes it it more map to the cdk vagrant boxes (if that is a concern). In other words, the cdk vagrant boxes currently include it as well.
