### ISSUE TITLE
RFE: include vasek's docker aliases

### ISSUE THREAD

**Issue by goern** [LalatenduMohanty/centos7-container-app-vagrant-box#15]
include the docker aliases [1] of vpavlin wihtin the base image, they are pretty handy...

[1] - https://github.com/vpavlin/docker-tools/blob/master/bash_aliases_docker

**Comment by kbsingh** [comment]
+1 looks like a good candidate for .bash_profile for user vagrant.

**Comment by LalatenduMohanty** [comment]
@goern looks good to me

**Comment by LalatenduMohanty** [comment]
This project has been merged witth [projectatomic/adb-atomic-developer-bundle](https://github.com/projectatomic/adb-atomic-developer-bundle)

All future development will happen at [projectatomic/adb-atomic-developer-bundle](https://github.com/projectatomic/adb-atomic-developer-bundle)

_All issues have been moved to the new [gitrepo](https://github.com/projectatomic/adb-atomic-developer-bundle)._
