### ISSUE TITLE
RFE: Adding a local docker registry in the vagrant box

### ISSUE THREAD

**Issue by langdon** [LalatenduMohanty/centos7-container-app-vagrant-box#16]
Was thinking it might be nice to ship this vm with a running docker registry (and/or docker-registry-ui ) either direct or in kube. I know I always end up needing one to work on atomicapps, but I think it is arguable.

**Comment by kbsingh** [comment]
I believe the plan was to find a way to integrate a build / render service for the layered images and couple that with the registry / delivery mechanism. If we can, I would recommend we hold off implementing the registry / delivery plan before we have clarity on the build/render process as well.

This is something we should definitely have ( maybe hooked in via a CI process as well ).

**Comment by LalatenduMohanty** [comment]
@kbsingh @whitel I think I would need help on this.

**Comment by LalatenduMohanty** [comment]
As discussed with @whitel and @kbsingh 
The local registry will be useful for developers in below scenarios 
- when  the container is being developed
  *\* The stuff is still very broken so he/she doesn't need ci yet
  *\* Is local copies of stuff I am using so I can be off-line (or not chewing up bandwidth). 

This is _not_ the registry we need to expose but just for dev/local-test

**Comment by LalatenduMohanty** [comment]
How ever the question now is 
- Should we bake the docker container for local registry in the vagrant box?
- Or, should we install docker-registry rpm (available in centos-extras)?

The key difference here is 'run on host' Vs 'run in container' ? @kbsingh  @whitel ?

**Comment by LalatenduMohanty** [comment]
As discussed, adding the  docker-registry to the vagrant box.

**Comment by langdon** [comment]
A couple comments: 1) should we warn the user that a vagrant destroy will blow away the contents of the registry the user added? or is that obvious? 2) we should open another ticket for the registry-ui.

**Comment by LalatenduMohanty** [comment]
@whitel Yeah, we need to work on the documentation for this
