### ISSUE TITLE
Build a secondary bleeding-dev box that tracks upstream versions closer

### ISSUE THREAD

**Issue by kbsingh** [LalatenduMohanty/centos7-container-app-vagrant-box#17]
It might be a good option to create a second vagrant box that tracks all the upstream versions for the core components we care about here : atomic, kuberneties and docker ( maybe from the virt7-sig ? ) 

This would be in addition to the default dev box that continues to track downstream versions of these components ( to match the default CentOS-7/x86_64 user experience ).

**Comment by LalatenduMohanty** [comment]
@kbsingh This is something I had in my mind. It is a good idea

**Comment by LalatenduMohanty** [comment]
This is tracked at utb (upstream tracker build) branch https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/tree/utb

**Comment by LalatenduMohanty** [comment]
This project has been merged witth [projectatomic/adb-atomic-developer-bundle](https://github.com/projectatomic/adb-atomic-developer-bundle)

All future development will happen at [projectatomic/adb-atomic-developer-bundle](https://github.com/projectatomic/adb-atomic-developer-bundle)

_All issues have been moved to the new [gitrepo](https://github.com/projectatomic/adb-atomic-developer-bundle)._
