### ISSUE TITLE
The default sync folder should be "/vagrant" inside the Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [LalatenduMohanty/centos7-container-app-vagrant-box#50]
As per upstream Vagrant box documentation [1] , the  default sysnc folder should be "/vagrant". Thanks to @bexelbie for bringing this to notice.

[1] https://docs.vagrantup.com/v2/synced-folders/

**Comment by bexelbie** [comment]
LGTM based on the test image

**Comment by LalatenduMohanty** [comment]
Fixed the issue in master
