### ISSUE TITLE
RFE: Increase the default RAM to 1GB for the Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [LalatenduMohanty/centos7-container-app-vagrant-box#7]
Currently the default RAM is 512MB. We need to increase it to 2GB at least.

**Comment by LalatenduMohanty** [comment]
https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/pull/8 should fix the issue

**Comment by LalatenduMohanty** [comment]
Also I need to find out how users will get the modified Vagrantfile when they use the image from https://atlas.hashicorp.com/lalatendum/boxes/nulecule-dev

That means `vagrant init lalatendum/nulecule-dev` should get the modified Vagrant file.

**Comment by kbsingh** [comment]
2GB seems excessive, can we start with 1GB and see if the problems are resolved. Atleast on my laptop, I only have 8GB of ram and dont want to lose 2GB to the vagrant process unless I really haveto. Do you know why the request went from 1GB to 2GB ?

**Comment by LalatenduMohanty** [comment]
I found out that we can change the default RAM of the box while building the box in Koji/image factory 

"koji -p cbs image-build --help" 
 params = ['ovf_cpu_count','ovf_memory_mb','ovf_name',
'rhevm_default_display_type','rhevm_description','rhevm_os_descriptor',
'vsphere_product_name','vsphere_product_vendor_name','vsphere_product_version',
                      'vsphere_virtual_system_type',
                      'vagrant_sync_directory']

**Comment by LalatenduMohanty** [comment]
This project has been merged witth [projectatomic/adb-atomic-developer-bundle](https://github.com/projectatomic/adb-atomic-developer-bundle)

All future development will happen at [projectatomic/adb-atomic-developer-bundle](https://github.com/projectatomic/adb-atomic-developer-bundle)

_All issues have been moved to the new [gitrepo](https://github.com/projectatomic/adb-atomic-developer-bundle)._
